services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ope
      POSTGRES_PASSWORD: ope
      POSTGRES_DB: ope
    ports:
      - "5432:5432"
    volumes:
      - ope_pg:/var/lib/postgresql/data
volumes:
  ope_pg:
